var mrw_menu_didattica = '<ul>'
+ '<li class="label">A</li>'
+ '<li><a href="http://www.mrwebmaster.it/ajax/">Ajax</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/android/">Android</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/apache/">Apache</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/asp/">ASP</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/aspnet/">ASP.Net</a></li>'
+ '<li class="label">C</li>'
+ '<li><a href="http://www.mrwebmaster.it/c/">C</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/csharp/">C#</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/cplusplus/">C++</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/cgi/">CGI</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/cloud/">Cloud</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/cms/">CMS</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/cold-fusion/">Cold Fusion</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/css/">CSS</a></li>'
+ '<li class="label">D</li>'
+ '<li><a href="http://www.mrwebmaster.it/database/">Database</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/delphi/">Delphi</a></li>'
+ '</ul><ul>'
+ '<li class="label">E</li>'
+ '<li><a href="http://www.mrwebmaster.it/editor/">Editor</a></li>'
+ '<li class="label">F</li>'
+ '<li><a href="http://www.mrwebmaster.it/flash/">Flash</a></li>'
+ '<li class="label">G</li>'
+ '<li><a href="http://www.mrwebmaster.it/grafica/">Grafica</a></li>'
+ '<li class="label">H</li>'
+ '<li><a href="http://www.mrwebmaster.it/hosting/">Hosting</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/html/">HTML</a></li>'
+ '<li class="label">I</li>'
+ '<li><a href="http://www.mrwebmaster.it/iis/">IIS</a></li>'
+ '<li class="label">J</li>'
+ '<li><a href="http://www.mrwebmaster.it/java/">Java</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/javascript/">Javascript</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/jquery/">jQuery</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/jsp/">JSP</a></li>'
+ '<li class="label">L</li>'
+ '<li><a href="http://www.mrwebmaster.it/leggi-fisco/">Leggi e Fisco</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/linux/">Linux</a></li>'
+ '</ul><ul>'
+ '<li class="label">M</li>'
+ '<li><a href="http://www.mrwebmaster.it/macosx/">Mac OS X</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/access/">Microsoft Access</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/sql-server/">Microsoft SQL Server</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/mobile/">Mobile</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/mysql/">MySQL</a></li>'
+ '<li class="label">O</li>'
+ '<li><a href="http://www.mrwebmaster.it/oracle/">Oracle</a></li>'
+ '<li class="label">P</li>'
+ '<li><a href="http://www.mrwebmaster.it/paint-shop-pro/">Paint Shop Pro</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/perl/">Perl</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/photoshop/">Photoshop</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/php/">PHP</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/primi-passi/">Primi Passi</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/programmazione/">Programmazione</a></li>'
+ '<li class="label">R</li>'
+ '<li><a href="http://www.mrwebmaster.it/reti/">Reti</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/ruby/">Ruby</a></li>'
+ '</ul><ul>'
+ '<li class="label">S</li>'
+ '<li><a href="http://www.mrwebmaster.it/sicurezza/">Sicurezza</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/sql/">SQL</a></li>'
+ '<li class="label">T</li>'
+ '<li><a href="http://www.mrwebmaster.it/the-gimp/">The Gimp</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/tomcat/">TomCat</a></li>'
+ '<li class="label">V</li>'
+ '<li><a href="http://www.mrwebmaster.it/vbnet/">VB.Net</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/visual-basic/">Visual Basic</a></li>'
+ '<li class="label">W</li>'
+ '<li><a href="http://www.mrwebmaster.it/web-design/">Web Design</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/web-marketing/">Web Marketing</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/webserver/">Web Server</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/windows/">Windows</a></li>'
+ '<li class="label">X</li>'
+ '<li><a href="http://www.mrwebmaster.it/xml/">XML</a></li>'
+ '</ul>';
var mrw_menu_download = '<ul>'
+ '<li><a href="http://www.mrwebmaster.it/software/">Software</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/script/">Script</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/plugin-cms/">Plugin CMS</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/flashmovies/">Flash Movies</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/soundloops/">Sound Loops</a></li>'
+ '<li><a href="http://www.mrwebmaster.it/templates/">Templates</a></li>'
+ '</ul>';
var mrw_menu_risorse = '<ul>'
+ '<li><a href="http://www.mrwebmaster.it/webapps/">WebApps</a></li>'
+ '</ul>';
var mrw_menu_servizi = '<ul>'
+ '<li><a href="http://tools.mrwebmaster.it/">Webmaster Tools</a></li>'
+ '<li><a href="http://toolset.mrwebmaster.it/">Toolset.it</a></li>'
+ '<li><a href="http://sitemarket.mrwebmaster.it/">SiteMarket.it</a></li>'
+ '<li><a href="http://hosting.mrwebmaster.it/">NuovoHosting.it</a></li>'
+ '<li><a href="http://webgrafica.mrwebmaster.it/">Web Grafica</a></li>'
+ '<li><a href="http://font.mrwebmaster.it/">Font Gratis</a></li>'
+ '</ul>';
$(function(){
$('#menu_didattica').html(mrw_menu_didattica);
$('#menu_download').html(mrw_menu_download);
$('#menu_risorse').html(mrw_menu_risorse);
$('#menu_servizi').html(mrw_menu_servizi);
});